### ISSUE TITLE
The Newsletter is breaking the layout of the WordPress Dashboard

### ISSUE THREAD

**Issue by NickOrtiz** [varunsridharan/WooCommerce-Single-Product-Checkout#5]
![image](https://user-images.githubusercontent.com/5807951/27650541-822175aa-5bf2-11e7-83ee-167a9aa24d7c.png)

It is possible that this is a conflict, or just an issue with the newer version of WordPress, if you'd like me to submit a Pull Request with a fix I'd be happy to do so.

**Comment by technofreaky** [comment]
Hi,

I am not sure which is making the issue. but that newsletter will be removed in upcoming update
